language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - ${HOME}/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - cp .env.example .env
  - php artisan key:generate

script:
  - phpunit
