language: php

php:
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - ${HOME}/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs

script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: false
  slack:
    secure: aCaquKjdnuv74NFMGRICjjq8NYO6fG9YTMItIvbnoNBz2XTpnzDLr20TGXdZJl+V0xBSik4uCzlXjbrZ5HhKx8kHNBn97NGrgqMoPAZ30IvpFzU1Mb4uJndv7WxHvS1Qs9jmi6c3Ws8cCusnUOZA8WQyiD6SJq3B6QbqaT6toEzgdBP76Y6Yka1MpFh7rLweOhrE6AEnEEhWTRpk5AVIqQhgZd8KgyZW+/X6yVmsCCA0RL+BKjcg1KuPFvxSXVfEnyS90m+BjMxoxNuuh3F4RJVci9FqdJbKGRlxzPO6ilUDn2WEhgfyS5JD4raQ+v/QaUpJhl2atwVujZPRlIXQPUobjtMkzM0vh1qd3qKSVytTl+mCNw+OYtK6BXyBEwfsvKb0gJa4fiuDJ3uUuL/MUSEnTDS0W11MUQCT0pfmY7WjWxZh97Sv2bVsGfV6rSo5WSNDYXfun4lOnK9QWe+FrJJl/EfnltlE0JVV5YVxzwpYzxR66FTmms58I9lfz7ZJRR0eNtlGoeo7hkDERAYj9j6ZOCBFtCLrZJil7avBUhjSTwpiUuOJnHTwywaPksrKKsmFdBMnKsLDS4+RlRXURkbMqcBMZq3pXjT8DK12/jFkp4D5dH3+e1QksdXbR+DpMYvXDYHUkV5HWpRazLOfhEMMNaFb6yidDR1rPIjfHzU=
