version: '3'
services:
  workspace:
    build: ./docker/workspace
    volumes:
      - .:/var/www:cached
    tty: true
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/etc/pki/nginx:/etc/pki/nginx
      - ./docker/nginx/var/log/nginx:/var/log/nginx
      - phpsocket:/var/run
    tty: true
    ports:
      - "8080:80"
      - "4443:443"
    depends_on:
      - workspace
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - .:/var/www:cached
      - ./docker/php-fpm/usr/local/etc/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpsocket:/var/run
    tty: true
    depends_on:
      - workspace
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis

volumes:
  mysql:
    driver: local
  phpsocket:
    driver: local
